### ISSUE TITLE
Undercutting/Search bug

### ISSUE THREAD

**Issue by jrob8577** [jrob8577/AuctionatorAddon#36]
Crafted Malevolent Gladiator's Barrier

Auction Connecting Valve

I've had a bunch, but right now, these two, that are not selling correctly, they aren't able to sell "4 stacks of 1", I can have 4 in my bag, it gives the "You do not have enough items" error, even when I have 4 in my bags. 

The other problem, it's not finding existing auctions with those items, and I end up being undercut by existing auctions when I reset prices because I don't even see the other tiems in the Auctionator - Sell page, but they will show up in the default system "Browse" page. 

Reported by http://www.curse.com/users/fraNkMinion on 7/6/2015
http://www.curse.com/addons/wow/auctionator?comment=5579

**Comment by pmc01** [comment]
One problem is the item link format changed so there are now 2 fields between level and instanceDifficultyID. The second problem is that item links are not always the same for identical items and can contain extra "junk". Some identical auctioneer parts contain :1: or :4: in the link. The staged bonusids for identical items can be in any order and any number, like 525:533:900 or 530:525 could describe the same item.

I came up with my own workaround but it's not 100% so I didn't post it. The workaround is to insert the following code at line 527 of zcUtils.lua, right after "table.sort (bonus)":

if bonusIDcount > 1 then bonusIDcount = bonusIDcount-1 end

**Comment by jrob8577** [comment]
Thanks for the detailed investigation!  I'm out of town and away from my development machine, but I'm planning on fixing bugs all next week (as well as beginning to clean up the code a little).

**Comment by jrob8577** [comment]
@pmc01 Taking a look at this now, if you're around can you buzz me in-game: jrob#1979

**Comment by jrob8577** [comment]
Should have been addressed in 3.2.6 item link updates
