### ISSUE TITLE
Bug Report: zcUtils.lua:1067: bad argument 1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by averlyn30** [jrob8577/AuctionatorAddon#37]
Just got this before a Kazzak pull, after a CRZ transfer for the raid group.

 Interface\AddOns\Auctionator\zcUtils.lua:1067: bad argument #1 to 'pairs' (table expected, got nil)

VERS:3.2.4   MEM:   987 KB   DB:27   SE:1  SL:2  FSCHUNK:<nil>  DBVERS:4

REALMS: , Stormrage_Alliance (27), Trollbane_Horde (0)

STACK: pairs > CopyDeep > Atr_OnBagUpdate > Atr_EventHandler

ADDONS: , AtlasLoot, Auctionator, BagSync, BankStack, FarmHud, FarmIt2, GatherMate2, HandyNotes, MageNuggets, MasterPlanA, MogIt, myBigIgnite, Paste, Postal, Routes, Skada, TomTom, WeakAuras, XToLevel, SVUI_!Core, SVUI_ActionBars, SVUI_Auras, SVUI_Chat, SVUI_Inventory, SVUI_Maps, SVUI_NamePlates, SVUI_QuestTracker, SVUI_Skins, SVUI_Tooltip, SVUI_UnitFrames, SVUI_CraftOMatic, WoWPro, DBM

**Comment by jrob8577** [comment]
Thanks!  I'm still going through curse comments and assembling bugs, but this looks like one I've seen - hope to be getting to a bug fix release in a week after orienting in the codebase.

**Comment by jrob8577** [comment]
I'm able to re-create this by passing nil values in from the caller `Atr_OnBagUpdate`.  My guess is that it's a timing issue, but I haven't been able to recreate by zoning.  Would you mind taking a dev copy of Auctionator with a minor patch to see if this is fixed (and still working)?
