### ISSUE TITLE
Gbank and Screen freezing for 3-5 seconds.

### ISSUE THREAD

**Issue by Sellstorm** [jrob8577/AuctionatorAddon#43]
http://i.imgur.com/tWpVN3s.jpg?2

When u try placing an item into the gbank from ur bags u get spammed with that wall of unknown as the screenshot says....It is auctionator doing it...I love the addon and hope it get fixed.  At first I thought it was TSM3,,,but further investigation confirmed its ur addon.  The screen will freeze for like 3-5 seconds then place the item in...it does that for the majority of items.....one by one.

**Comment by jrob8577** [comment]
Thanks for the bug report!!  Can you share your debugging steps to verify it wasn't TMS3?  Did you get any LUA errors, or was this just observed behavior?

I'll be digging into the bugs next week (starting 8/24), so will make sure to take a look - any additional information would be appreciated!

**Comment by Sellstorm** [comment]
I contacted the developers of tsm after the bug was starting to get worse.   They confirmed after looking into it that it was auctionator.  If i disable auctionator....it no longer occurs....keeping the same other addons.  At first I thought it was The Undermine journal, so i disabled and still happened.  I re-enabled....then disabled auctionator to be sure.

**Comment by Sellstorm** [comment]
I should note....it only occurs on one toon tho...my ah/ bank toon that has 1000s of items / auctions.

**Comment by jrob8577** [comment]
@Sellstorm Installing TSM to debug - which of the modules do you have installed?

**Comment by jrob8577** [comment]
Some links for myself:

https://www.tradeskillmaster.com/addon/overview
http://www.curse.com/addons/wow/tradeskill-master

**Comment by Medivha** [comment]
i have the same problem and create a issue without reading the other ones first^^ sry her the link
https://github.com/jrob8577/AuctionatorAddon/issues/58

all detailed information inside (screenshot version etc)

**Comment by jrob8577** [comment]
Alrighty I managed to dig into this, and discovered that it is the way that TSM is working with Battle Pets in the GuildBank.  Unfortunately, there's nothing I can do to prevent this, see notes on my findings in #58.  Thanks for the reports!  

I'm keeping the bug flagged in case I brainstorm a way to work around how TSM is working with the guild bank, but it would be a lot of work to address an issue that should not have been introduced...
