### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MegFr** [jrob8577/AuctionatorAddon#49]
Interface\AddOns\Auctionator\Auctionator.lua:1274: attempt to index global 'AtrScanningTooltip' (a nil value)

VERS:3.2.4   MEM:  1018 KB   DB:137   SE:0  SL:2  FSCHUNK:<nil>  DBVERS:4

REALMS: , Earthen Ring_Alliance (137)

STACK: Atr_GetSellItemInfo > Atr_SetDepositText > Atr_UpdateUI_SellPane > Atr_UpdateUI > Atr_Idle > Atr_OnUpdate

ADDONS: , Auctionator, Pawn

**Comment by jrob8577** [comment]
Would you happen to remember what you were doing when this occurred?

**Comment by MegFr** [comment]
Yes it first occured when I tried to sell some gold.
R. Cazeneuve


__________________________________
Sent from eM Client | www.emclient.com



------ Original Message ------

**Comment by jrob8577** [comment]
Duplicates #6 (closing this one, tracking it in issue 6)
